using VehicleIQ.API.DTOs;
using VehicleIQ.API.Exceptions;
using VehicleIQ.API.Models.Entities;
using VehicleIQ.API.Models.Enums;
using VehicleIQ.API.Repositories.Interfaces;
using VehicleIQ.API.Services.Interfaces;

namespace VehicleIQ.API.Services.Implementations;

public class ExpenseService : IExpenseService
{
    private readonly IExpenseRepository _expenseRepository;
    private readonly IVehicleRepository _vehicleRepository;

    public ExpenseService(IExpenseRepository expenseRepository, IVehicleRepository vehicleRepository)
    {
        _expenseRepository = expenseRepository;
        _vehicleRepository = vehicleRepository;
    }

    public async Task<IReadOnlyList<ExpenseDto>> GetExpensesByUserIdAsync(int userId)
    {
        var expenses = await _expenseRepository.GetByUserIdAsync(userId);
        return expenses.Select(e => e.ToDto()).ToList().AsReadOnly();
    }

    public async Task<IReadOnlyList<ExpenseDto>> GetExpensesByVehicleIdAsync(int vehicleId, int userId)
    {
        // Guard: Verify vehicle exists and belongs to user
        var vehicle = await _vehicleRepository.GetByIdAndUserIdAsync(vehicleId, userId);
        if (vehicle == null)
        {
            throw new NotFoundException($"Vehicle with ID {vehicleId} was not found.");
        }

        var expenses = await _expenseRepository.GetByVehicleIdAsync(vehicleId);
        return expenses.Select(e => e.ToDto()).ToList().AsReadOnly();
    }

    public async Task<ExpenseDto> CreateExpenseAsync(CreateExpenseRequest request, int userId)
    {
        if (request.VehicleId.HasValue)
        {
            var vehicle = await _vehicleRepository.GetByIdAndUserIdAsync(request.VehicleId.Value, userId);
            if (vehicle == null)
            {
                throw new NotFoundException($"Vehicle with ID {request.VehicleId.Value} was not found.");
            }
        }

        var expense = request.ToEntity(userId);
        var created = await _expenseRepository.AddAsync(expense);
        return created.ToDto();
    }

    public async Task<ExpenseDto> CreateSystemExpenseAsync(
        int userId, 
        int? vehicleId, 
        DateTime date, 
        ExpenseCategory category, 
        decimal amount, 
        string description, 
        string referenceType, 
        int referenceId)
    {
        var expense = new Expense
        {
            UserId = userId,
            VehicleId = vehicleId,
            Date = date,
            Category = category,
            Amount = amount,
            Description = description,
            ReferenceType = referenceType,
            ReferenceId = referenceId
        };

        var created = await _expenseRepository.AddAsync(expense);
        return created.ToDto();
    }

    public async Task DeleteExpenseAsync(int id, int userId)
    {
        var expense = await _expenseRepository.GetByIdAsync(id);
        if (expense == null || expense.UserId != userId)
        {
            throw new NotFoundException($"Expense with ID {id} was not found.");
        }

        if (!string.IsNullOrEmpty(expense.ReferenceType))
        {
            throw new BadRequestException("This expense was automatically generated by another record (e.g. Fuel Log or Service Bill) and cannot be deleted directly. Please delete the source record instead.");
        }

        await _expenseRepository.DeleteAsync(expense);
    }
}
